version: "3"

services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOW_IP_RANGE: ${ALLOW_IP_RANGE}
    ports:
      - "5432:5432"
    volumes:
      - ./postgis:/var/lib/postgresql
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    networks:
      - net_postgis

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - postgis

networks:
  net_postgis:
